<a href="https://colab.research.google.com/github/Jumamurod-Aralov/27.03.2026---New-Unity-Input-System-Migration-Framework/blob/main/Encoding_%26_Scaling_with_Real_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Step 1 — Load the dataset

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/IBM/telco-customer-churn-on-icp4d/master/data/Telco-Customer-Churn.csv"

df = pd.read_csv(url)

Step 2 — Find the number of rows and columns

In [ ]:
print("Dataset shape:", df.shape)
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Dataset shape: (7043, 21)
Number of rows: 7043
Number of columns: 21

Step 3 — Inspect the data

In [ ]:
display(df.head())

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [ ]:
for column in df.columns:
    print(f"\n{column}")
    print(df[column].dropna().unique()[:10])

customerID
['7590-VHVEG' '5575-GNVDE' '3668-QPYBK' '7795-CFOCW' '9237-HQITU'
 '9305-CDSKC' '1452-KIOVK' '6713-OKOMC' '7892-POOKP' '6388-TABGU']

gender
['Female' 'Male']

SeniorCitizen
[0 1]

Partner
['Yes' 'No']

Dependents
['No' 'Yes']

tenure
[ 1 34  2 45  8 22 10 28 62 13]

PhoneService
['No' 'Yes']

MultipleLines
['No phone service' 'No' 'Yes']

InternetService
['DSL' 'Fiber optic' 'No']

OnlineSecurity
['No' 'Yes' 'No internet service']

OnlineBackup
['Yes' 'No' 'No internet service']

DeviceProtection
['No' 'Yes' 'No internet service']

TechSupport
['No' 'Yes' 'No internet service']

StreamingTV
['No' 'Yes' 'No internet service']

StreamingMovies
['No' 'Yes' 'No internet service']

Contract
['Month-to-month' 'One year' 'Two year']

PaperlessBilling
['Yes' 'No']

PaymentMethod
['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']

MonthlyCharges
[ 29.85  56.95  53.85  42.3   70.7   99.65  89.1   29.75 104.8   56.15]

TotalCharges
['29.85' '1889.5' '108.15' '1840.75' '151.65' '820.5' '1949.4' '301.9'
 '3046.05' '3487.95']

Churn
['No' 'Yes']

Step 4 — Build your data dictionary

In [ ]:
import pandas as pd

data_dictionary = pd.DataFrame({
    "Column name": df.columns,
    "Type": [
        "Numeric" if pd.api.types.is_numeric_dtype(df[col])
        else "Categorical"
        for col in df.columns
    ],
    "Example value": [
        df[col].dropna().iloc[0] if df[col].notna().any() else None
        for col in df.columns
    ]
})

display(data_dictionary)

         Column name         Type     Example value
0         customerID  Categorical        7590-VHVEG
1             gender  Categorical            Female
2      SeniorCitizen      Numeric                 0
3            Partner  Categorical               Yes
4         Dependents  Categorical                No
5             tenure      Numeric                 1
6       PhoneService  Categorical                No
7      MultipleLines  Categorical  No phone service
8    InternetService  Categorical               DSL
9     OnlineSecurity  Categorical                No
10      OnlineBackup  Categorical               Yes
11  DeviceProtection  Categorical                No
12       TechSupport  Categorical                No
13       StreamingTV  Categorical                No
14   StreamingMovies  Categorical                No
15          Contract  Categorical    Month-to-month
16  PaperlessBilling  Categorical               Yes
17     PaymentMethod  Categorical  Electronic check
18    MonthlyCharges      Numeric             29.85
19      TotalCharges  Categorical             29.85
20             Churn  Categorical                No

In [ ]:
meanings = {
    "customerID": "Unique customer identifier",
    "gender": "Customer's recorded gender",
    "SeniorCitizen": "Whether the customer is a senior citizen",
    "Partner": "Whether the customer has a partner",
    "Dependents": "Whether the customer has dependents",
    "tenure": "Number of months with the company",
    "PhoneService": "Whether the customer has phone service",
    "MultipleLines": "Whether the customer has multiple phone lines",
    "InternetService": "Type of internet service",
    "OnlineSecurity": "Whether online security is included",
    "OnlineBackup": "Whether online backup is included",
    "DeviceProtection": "Whether device protection is included",
    "TechSupport": "Whether technical support is included",
    "StreamingTV": "Whether streaming TV is included",
    "StreamingMovies": "Whether streaming movies are included",
    "Contract": "Customer's contract type",
    "PaperlessBilling": "Whether paperless billing is enabled",
    "PaymentMethod": "Customer's payment method",
    "MonthlyCharges": "Current monthly charges",
    "TotalCharges": "Total charges recorded for the customer",
    "Churn": "Whether the customer left the company"
}

data_dictionary.insert(
    1,
    "Real-life meaning",
    data_dictionary["Column name"].map(meanings)
)

display(data_dictionary)

,Column name,Real-life meaning,Type,Example value
0,customerID,Unique customer identifier,Categorical,7590-VHVEG
1,gender,Customer's recorded gender,Categorical,Female
2,SeniorCitizen,Whether the customer is a senior citizen,Numeric,0
3,Partner,Whether the customer has a partner,Categorical,Yes
4,Dependents,Whether the customer has dependents,Categorical,No
5,tenure,Number of months with the company,Numeric,1
6,PhoneService,Whether the customer has phone service,Categorical,No
7,MultipleLines,Whether the customer has multiple phone lines,Categorical,No phone service
8,InternetService,Type of internet service,Categorical,DSL
9,OnlineSecurity,Whether online security is included,Categorical,No
10,OnlineBackup,Whether online backup is included,Categorical,Yes
11,DeviceProtection,Whether device protection is included,Categorical,No
12,TechSupport,Whether technical support is included,Categorical,No
13,StreamingTV,Whether streaming TV is included,Categorical,No
14,StreamingMovies,Whether streaming movies are included,Categorical,No
15,Contract,Customer's contract type,Categorical,Month-to-month
16,PaperlessBilling,Whether paperless billing is enabled,Categorical,Yes
17,PaymentMethod,Customer's payment method,Categorical,Electronic check
18,MonthlyCharges,Current monthly charges,Numeric,29.85
19,TotalCharges,Total charges recorded for the customer,Categorical,29.85
20,Churn,Whether the customer left the company,Categorical,No

In [ ]:
categorical_columns = [
    "customerID", "gender", "SeniorCitizen", "Partner",
    "Dependents", "PhoneService", "MultipleLines",
    "InternetService", "OnlineSecurity", "OnlineBackup",
    "DeviceProtection", "TechSupport", "StreamingTV",
    "StreamingMovies", "Contract", "PaperlessBilling",
    "PaymentMethod", "Churn"
]

data_dictionary.loc[
    data_dictionary["Column name"].isin(categorical_columns),
    "Type"
] = "Categorical"

display(data_dictionary)

,Column name,Real-life meaning,Type,Example value
0,customerID,Unique customer identifier,Categorical,7590-VHVEG
1,gender,Customer's recorded gender,Categorical,Female
2,SeniorCitizen,Whether the customer is a senior citizen,Categorical,0
3,Partner,Whether the customer has a partner,Categorical,Yes
4,Dependents,Whether the customer has dependents,Categorical,No
5,tenure,Number of months with the company,Numeric,1
6,PhoneService,Whether the customer has phone service,Categorical,No
7,MultipleLines,Whether the customer has multiple phone lines,Categorical,No phone service
8,InternetService,Type of internet service,Categorical,DSL
9,OnlineSecurity,Whether online security is included,Categorical,No
10,OnlineBackup,Whether online backup is included,Categorical,Yes
11,DeviceProtection,Whether device protection is included,Categorical,No
12,TechSupport,Whether technical support is included,Categorical,No
13,StreamingTV,Whether streaming TV is included,Categorical,No
14,StreamingMovies,Whether streaming movies are included,Categorical,No
15,Contract,Customer's contract type,Categorical,Month-to-month
16,PaperlessBilling,Whether paperless billing is enabled,Categorical,Yes
17,PaymentMethod,Customer's payment method,Categorical,Electronic check
18,MonthlyCharges,Current monthly charges,Numeric,29.85
19,TotalCharges,Total charges recorded for the customer,Categorical,29.85
20,Churn,Whether the customer left the company,Categorical,No

In [ ]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [ ]:
pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.values
})

              Column Data Type
0         customerID    object
1             gender    object
2      SeniorCitizen     int64
3            Partner    object
4         Dependents    object
5             tenure     int64
6       PhoneService    object
7      MultipleLines    object
8    InternetService    object
9     OnlineSecurity    object
10      OnlineBackup    object
11  DeviceProtection    object
12       TechSupport    object
13       StreamingTV    object
14   StreamingMovies    object
15          Contract    object
16  PaperlessBilling    object
17     PaymentMethod    object
18    MonthlyCharges   float64
19      TotalCharges    object
20             Churn    object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [ ]:
for col in df.columns:
    print(col, "→", df[col].dropna().unique()[:5])

customerID → ['7590-VHVEG' '5575-GNVDE' '3668-QPYBK' '7795-CFOCW' '9237-HQITU']
gender → ['Female' 'Male']
SeniorCitizen → [0 1]
Partner → ['Yes' 'No']
Dependents → ['No' 'Yes']
tenure → [ 1 34  2 45  8]
PhoneService → ['No' 'Yes']
MultipleLines → ['No phone service' 'No' 'Yes']
InternetService → ['DSL' 'Fiber optic' 'No']
OnlineSecurity → ['No' 'Yes' 'No internet service']
OnlineBackup → ['Yes' 'No' 'No internet service']
DeviceProtection → ['No' 'Yes' 'No internet service']
TechSupport → ['No' 'Yes' 'No internet service']
StreamingTV → ['No' 'Yes' 'No internet service']
StreamingMovies → ['No' 'Yes' 'No internet service']
Contract → ['Month-to-month' 'One year' 'Two year']
PaperlessBilling → ['Yes' 'No']
PaymentMethod → ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
MonthlyCharges → [29.85 56.95 53.85 42.3  70.7 ]
TotalCharges → ['29.85' '1889.5' '108.15' '1840.75' '151.65']
Churn → ['No' 'Yes']

In [ ]:
data_dictionary.to_csv("data_dictionary.csv", index=False)

In [ ]:
from google.colab import files
files.download("data_dictionary.csv")

In [ ]:
data_dictionary.to_excel("data_dictionary.xlsx", index=False)

In [ ]:
files.download("data_dictionary.xlsx")

### **Day 2. Explore the Data (EDA)**

1.1 Check the dataset shape

In [ ]:
print("Rows and columns:", df.shape)
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Rows and columns: (7043, 21)
Number of rows: 7043
Number of columns: 21

1.2 Check missing values in every column

In [ ]:
missing = pd.DataFrame({
    "Missing count": df.isnull().sum(),
    "Missing percentage": (df.isnull().mean() * 100).round(2)
})

display(missing)

                  Missing count  Missing percentage
customerID                    0                 0.0
gender                        0                 0.0
SeniorCitizen                 0                 0.0
Partner                       0                 0.0
Dependents                    0                 0.0
tenure                        0                 0.0
PhoneService                  0                 0.0
MultipleLines                 0                 0.0
InternetService               0                 0.0
OnlineSecurity                0                 0.0
OnlineBackup                  0                 0.0
DeviceProtection              0                 0.0
TechSupport                   0                 0.0
StreamingTV                   0                 0.0
StreamingMovies               0                 0.0
Contract                      0                 0.0
PaperlessBilling              0                 0.0
PaymentMethod                 0                 0.0
MonthlyCharges                0                 0.0
TotalCharges                  0                 0.0
Churn                         0                 0.0

1.3 Check empty text values

In [ ]:
empty_text = {}

for col in df.select_dtypes(include=["object"]).columns:
    empty_text[col] = df[col].apply(
        lambda x: isinstance(x, str) and x.strip() == ""
    ).sum()

display(pd.Series(empty_text, name="Empty text count"))

customerID           0
gender               0
Partner              0
Dependents           0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
TotalCharges        11
Churn                0
Name: Empty text count, dtype: int64

1.4 Check duplicate rows

In [ ]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [ ]:
display(df[df.duplicated(keep=False)].head(10))

Empty DataFrame
Columns: [customerID, gender, SeniorCitizen, Partner, Dependents, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges, Churn]
Index: []

[0 rows x 21 columns]

1.5 Check strange values

In [ ]:
for col in df.select_dtypes(include=["object"]).columns:
    print(f"\n{col}")
    print(df[col].value_counts(dropna=False))

customerID
customerID
3186-AJIEK    1
7590-VHVEG    1
5575-GNVDE    1
8775-CEBBJ    1
2823-LKABH    1
             ..
6713-OKOMC    1
1452-KIOVK    1
9305-CDSKC    1
9237-HQITU    1
7795-CFOCW    1
Name: count, Length: 7043, dtype: int64

gender
gender
Male      3555
Female    3488
Name: count, dtype: int64

Partner
Partner
No     3641
Yes    3402
Name: count, dtype: int64

Dependents
Dependents
No     4933
Yes    2110
Name: count, dtype: int64

PhoneService
PhoneService
Yes    6361
No      682
Name: count, dtype: int64

MultipleLines
MultipleLines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64

InternetService
InternetService
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64

OnlineSecurity
OnlineSecurity
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64

OnlineBackup
OnlineBackup
No                     3088
Yes                    2429
No internet service    1526
Name: count, dtype: int64

DeviceProtection
DeviceProtection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64

TechSupport
TechSupport
No                     3473
Yes                    2044
No internet service    1526
Name: count, dtype: int64

StreamingTV
StreamingTV
No                     2810
Yes                    2707
No internet service    1526
Name: count, dtype: int64

StreamingMovies
StreamingMovies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64

Contract
Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

PaperlessBilling
PaperlessBilling
Yes    4171
No     2872
Name: count, dtype: int64

PaymentMethod
PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

TotalCharges
TotalCharges
           11
20.2       11
19.75       9
20.05       8
19.9        8
           ..
130.15      1
3211.9      1
7843.55     1
2196.3      1
197.4       1
Name: count, Length: 6531, dtype: int64

Churn
Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [ ]:
display(df.describe().T)

,count,mean,std,min,25%,50%,75%,max
SeniorCitizen,7043.0,0.162147,0.368612,0.00,0.0,0.00,0.00,1.00
tenure,7043.0,32.371149,24.559481,0.00,9.0,29.00,55.00,72.00
MonthlyCharges,7043.0,64.761692,30.090047,18.25,35.5,70.35,89.85,118.75

In [ ]:
print("TotalCharges dtype:", df["TotalCharges"].dtype)
print(df["TotalCharges"].value_counts().head(10))

TotalCharges dtype: object
TotalCharges
         11
20.2     11
19.75     9
20.05     8
19.9      8
19.65     8
19.55     7
45.3      7
20.15     6
20.25     6
Name: count, dtype: int64

## Day 2 — Step 2, target balance

We need to understand how many customers churned before analyzing relationships between churn and other features.

In [ ]:
print("Churn counts:")
print(df["Churn"].value_counts())

print("\nChurn percentages:")
print((df["Churn"].value_counts(normalize=True) * 100).round(2))

Churn counts:
Churn
No     5174
Yes    1869
Name: count, dtype: int64

Churn percentages:
Churn
No     73.46
Yes    26.54
Name: proportion, dtype: float64

The dataset contains 7,043 customers, of whom 26.54% churned and 73.46% stayed. The target classes are imbalanced, so accuracy alone may not be sufficient to evaluate the model.